/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/attachments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload an attachment */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        /**
                         * Format: binary
                         * @description Allowlisted document, image or audio. The server validates size, name, MIME and signature/content before moving it out of quarantine.
                         */
                        file: string;
                        /** @enum {string} */
                        kind?: "document" | "image" | "audio";
                        session_id: string;
                    };
                };
            };
            responses: {
                /** @description JSON response */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Attachment"];
                    };
                };
                /** @description JSON response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description JSON response */
                413: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/attachments/{attachment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download an attachment */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Attachment id */
                    attachment_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Attachment bytes */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description JSON response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /**
         * Delete an attachment that was never linked to a message
         * @description Cleanup for the upload-then-send flow: removes an attachment still awaiting a message. Rejects attachments already attached to a message — use this only to compensate a failed send.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Attachment id */
                    attachment_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Attachment deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description JSON response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description JSON response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/books": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search books */
        get: {
            parameters: {
                query?: {
                    /** @description Filter by title */
                    title?: string;
                    /** @description Filter by author */
                    author?: string;
                    /** @description Filter by category */
                    category?: string;
                    /** @description Search title, author, category and summary */
                    q?: string;
                    /** @description Max items to return (1-200). Omit for the full unbounded list. */
                    limit?: number;
                    /** @description Items to skip before collecting results. Omit to start at 0. */
                    offset?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description JSON array response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Book"][];
                    };
                };
            };
        };
        put?: never;
        /** Create a book */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateBookRequest"];
                };
            };
            responses: {
                /** @description JSON response */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Book"];
                    };
                };
                /** @description JSON response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/books/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import a book from uploaded file */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        /**
                         * Format: binary
                         * @description .txt, .md, .json or .pdf containing title, author, category, year and summary. Content and declared MIME are validated; PDFs are subject to configured resource limits.
                         */
                        file: string;
                    };
                };
            };
            responses: {
                /** @description JSON response */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ImportBookResponse"];
                    };
                };
                /** @description JSON response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description JSON response */
                413: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/books/{book_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a book by id */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Book id */
                    book_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description JSON response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Book"];
                    };
                };
                /** @description JSON response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send a user message and create an assistant answer
         * @description Rate limited (RATE_LIMIT_CHAT_MESSAGES, default 20/min per IP).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SendMessageRequest"];
                    "multipart/form-data": {
                        attachment_kinds?: ("document" | "image" | "audio")[];
                        content?: string;
                        /** @description Files validated and linked to the user message within the same unit of work. */
                        files?: string[];
                        model?: string;
                        session_id: string;
                        /** @enum {string} */
                        thinking_mode?: "fast" | "balanced" | "deep";
                    };
                };
            };
            responses: {
                /** @description JSON response */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SendMessageResponse"];
                    };
                };
                /** @description JSON response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description JSON response */
                413: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description JSON response */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat/messages/{assistant_message_id}/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record LangSmith feedback for an assistant message */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Assistant message id */
                    assistant_message_id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["FeedbackRequest"];
                };
            };
            responses: {
                /** @description JSON response */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FeedbackResponse"];
                    };
                };
                /** @description JSON response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description JSON response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat/messages/{assistant_message_id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream assistant message via Server-Sent Events */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Assistant message id */
                    assistant_message_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description SSE token stream */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/event-stream": string;
                    };
                };
                /** @description JSON response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List chat sessions */
        get: {
            parameters: {
                query?: {
                    /** @description Max items to return (1-200). Omit for the full unbounded list. */
                    limit?: number;
                    /** @description Items to skip before collecting results. Omit to start at 0. */
                    offset?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description JSON array response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ChatSession"][];
                    };
                };
            };
        };
        put?: never;
        /** Create chat session */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateChatSessionRequest"];
                };
            };
            responses: {
                /** @description JSON response */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ChatSession"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a chat session and its messages */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Chat session id */
                    session_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Session deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description JSON response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /** Update chat session metadata */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Chat session id */
                    session_id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateChatSessionRequest"];
                };
            };
            responses: {
                /** @description JSON response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ChatSession"];
                    };
                };
                /** @description JSON response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/v1/chat/sessions/{session_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List messages from a session */
        get: {
            parameters: {
                query?: {
                    /** @description Max items to return (1-200). Omit for the full unbounded list. */
                    limit?: number;
                    /** @description Items to skip before collecting results. Omit to start at 0. */
                    offset?: number;
                };
                header?: never;
                path: {
                    /** @description Chat session id */
                    session_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description JSON array response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ChatMessage"][];
                    };
                };
                /** @description JSON response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description JSON response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HealthResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/semantic-search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run semantic search over local Python documents */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SemanticSearchRequest"];
                };
            };
            responses: {
                /** @description JSON response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SemanticSearchResponse"];
                    };
                };
                /** @description JSON response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Expose Prometheus metrics */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Prometheus text exposition format */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                    };
                };
                /** @description JSON response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Attachment: {
            /** Format: date-time */
            created_at: string;
            filename: string;
            id: string;
            /** @enum {string} */
            kind: "document" | "image" | "audio";
            mime_type: string;
            size: number;
            url: string;
        };
        Book: {
            author: string;
            category: string;
            /** Format: date-time */
            created_at: string;
            id: string;
            /** Format: date */
            publication_date: string;
            publication_year: number;
            summary: string;
            title: string;
        };
        ChatMessage: {
            attachments: components["schemas"]["Attachment"][];
            content: string;
            /** Format: date-time */
            created_at: string;
            id: string;
            /** @enum {string} */
            role: "user" | "assistant" | "system";
            session_id: string;
            /** @enum {string} */
            status: "pending" | "streaming" | "completed" | "failed";
            /** @enum {string|null} */
            thinking_mode: "fast" | "balanced" | "deep" | null;
            trace_id: string | null;
        };
        ChatSession: {
            /** Format: date-time */
            created_at: string;
            id: string;
            pinned: boolean;
            /** Format: date-time */
            pinned_at: string | null;
            title: string;
            /** Format: date-time */
            updated_at: string;
        };
        CreateBookRequest: {
            author: string;
            category?: string;
            /** Format: date */
            publication_date?: string;
            publication_year?: number;
            summary: string;
            title: string;
        };
        CreateChatSessionRequest: {
            title?: string;
        };
        ErrorResponse: {
            error: {
                code: string;
                details: {
                    [key: string]: unknown;
                };
                message: string;
            };
            request_id: string | null;
        };
        FeedbackRequest: {
            comment?: string;
            key?: string;
            score: number;
        };
        FeedbackResponse: {
            feedback_id?: string;
            reason?: string;
            recorded: boolean;
        };
        HealthResponse: {
            request_id: string | null;
            service: string;
            status: string;
        };
        ImportBookResponse: {
            book: components["schemas"]["Book"];
            extracted: {
                author: string;
                category: string;
                publication_year: number;
                summary: string;
                title: string;
            };
        };
        SemanticSearchRequest: {
            k?: number;
            query: string;
        };
        SemanticSearchResponse: {
            results: {
                document_id: string;
                excerpt: string;
                score: number;
                title: string;
            }[];
        };
        SendMessageRequest: {
            attachment_ids?: string[];
            content?: string;
            model?: string;
            session_id: string;
            /** @enum {string} */
            thinking_mode?: "fast" | "balanced" | "deep";
        };
        SendMessageResponse: {
            assistant_message: components["schemas"]["ChatMessage"];
            assistant_message_id: string;
            status: string;
            user_message_id: string;
        };
        UpdateChatSessionRequest: {
            pinned: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
